### ISSUE TITLE
about the global model world.gmm

### ISSUE THREAD

**Issue by AhmadKhattak** [ALIZE-Speaker-Recognition/android-alize#11]
Hi,

I’m trying to run the ALIZE android library for speaker verification, i’ve downloaded the library and followed the steps in https://github.com/ALIZE-Speaker-Recognition/android-alize 

however, i’m confused regarding the world.gmm file, i know its the universal background model but i don’t know how to generate it.

Edit: I've used another source on the web to generate a universal background model https://appliedmachinelearning.wordpress.com/2017/06/14/voice-gender-detection-using-gmms-a-python-primer/ the male.gmm model was generated following the link. Now, i'm trying to use this male.gmm model for the world.gmm model and use the train_data samples available in the link to perform a demo of speaker verification, however i'm getting the following error, 
<img width="1200" alt="screen shot 2018-03-17 at 2 55 53 pm" src="https://user-images.githubusercontent.com/6959644/37553978-a7b38fe0-29f3-11e8-85b2-7a341ebf05d6.png">

Any help would be much appreciated, Thanks !

**Comment by RITCHIEHuang** [comment]
@AhmadKhattak 
So how do you generate your ``word.gmm`` file ?
![image](https://user-images.githubusercontent.com/16410627/38741283-333d5400-3f6c-11e8-9e1b-9dc4da2fa885.png)

**Comment by AhmadKhattak** [comment]
@RITCHIEHuang to generate a world model, what i've been doing is from http://alize.univ-avignon.fr/ downloaded Tutorial for LIA_SpkDet — GMM/UBM System and then read through those .sh files to understand how to generate the world.gmm file.

Basically,

1. Extract MFCC features from your audio files using SPRO or HTK.
2. Perform Feature Normalization using the LIA_RAL library functions such as NormFeat, EnergyDetector.
3. Use the TrainWorld function from LIA_RAL library to generate your world.gmm (Universal Background Model)
