### ISSUE TITLE
SPro version

### ISSUE THREAD

**Issue by MashruraT** [ALIZE-Speaker-Recognition/android-alize#3]
In the documentation it is mentioned that SPro 5.0 which is available through the given link is not compatible to the project. But I did not find any newer version (revision 155 or higher) of SPro. Can you please share the compatible version of SPro?

**Comment by tevamerlin** [comment]
The latest revisions of SPro can be obtained from the Subversion server of the SPro project. The URL for it is: svn://scm.gforge.inria.fr/svnroot/spro/

As a convenience, I’ve uploaded the latest release (at the time of this writing) here:
[spro-5.0-157.tar.gz](https://github.com/ALIZE-Speaker-Recognition/android-alize/files/1460692/spro-5.0-157.tar.gz)

**Comment by MashruraT** [comment]
Thank you so much for your help!

I was trying to follow the instructions to generate the Alize module. But getting some errors. I am attaching the messages from Android Studio Console. But mainly the error looks like:

**CMake Error at CMakeLists.txt:96 (add_library):
    src/main/cpp/spro/sig.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: alize-native
-- Generating done
-- Build files have been written to: C:/Users/MT/Documents/AndroidStudioProjects/android-alize/alize/.externalNativeBuild/cmake/release/armeabi**

Can you suggest what I can do?
Thanks in advance.

[AndroidStudioErrors.txt](https://github.com/ALIZE-Speaker-Recognition/android-alize/files/1463528/AndroidStudioErrors.txt)

**Comment by radiolarian** [comment]
I had this issue too -- make sure you have CMake, LLDB and NDK installed through the SDK Manager. https://developer.android.com/studio/projects/add-native-code.html

**Comment by MashruraT** [comment]
Thank you!
