### ISSUE TITLE
Question about createSpeaModel

### ISSUE THREAD

**Issue by ra2637** [ALIZE-Speaker-Recognition/android-alize#4]
Hi, 
I'm having error in alizeSystem.createSpeaModel. The error message is as following

```log
W/System.err: AlizeSpkRec.AlizeException: [ FileNotFoundException 0x73732f4c80 ]
W/System.err:   message   = ""
W/System.err:   source file = /Users/ra2637/Workspace/alize/android-alize/alize/src/main/cpp/alize-core/src/FileReader.cpp
W/System.err:   line number = 101
W/System.err:   fileName = /data/user/0/com.example.android.voicerecognition/files//171111_073122.norm.prm
W/System.err:     at AlizeSpkRec.SimpleSpkDetSystem.createSpeakerModel(Native Method)
W
```
It looks like the system would like to read the `/data/user/0/com.example.android.voicerecognition/files//171111_073122.norm.prm` file and couldn't find it. I am not sure that should I provide the .prm file? or is it because the alize.cfg has wrong setting? 

I even tried to change the workDir to `/data/data/com.example.android.voicerecognition/files`  when create the SimpleSpkDetSystem instance, but I still cannot find this file in my device. 

I am really lost, I will be appreciated if you could help me out to know what's happened here. I also put my alize.cfg file as following.
```config
distribType			GD
maxLLK				200
minLLK				-200
bigEndian			false
saveMixtureFileFormat		RAW
loadMixtureFileFormat		RAW
loadFeatureFileFormat		SPRO4
featureServerBufferSize		ALL_FEATURES
featureFilesPath		/
mixtureFilesPath		data/

MAPAlgo				                MAPOccDep
loadFeatureFileExtension		.norm.prm
```

**Comment by ra2637** [comment]
I think I know what's happened there, The `loadFeatureFileFormat` should be RAW since I use .wav file.

**Comment by tevamerlin** [comment]
Hi,

Actually, I think the problem is linked to `loadFeatureFileExtension`, which is set to `.norm.prm` in your configuration.  In the method performing parameterization (in SimpleSpkDetSystem.cpp), the extension is hard-coded to `.prm` for the temporary feature file, while the rest of the code uses the extension specified in the configuration file.
We will fix this, but as a temporary solution, you can specify `.prm` for this parameter in your config file.

**Comment by ra2637** [comment]
HI,

You are so correct, actually I did many modify `loadFeatureFileExtension`  to `.prm` in my config file and I didn't realize that. Thanks.

**Comment by Ganerdene** [comment]
i facing this error help me please
