### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by nitinverma04** [ALIZE-Speaker-Recognition/android-alize#6]
I am getting following error while trying to initialize Alizesystem.
My AlizeDefault.cfg file is attached.

AlizeSpkRec.AlizeException: [ FileNotFoundException 0x7f8c8de0c0 ]
11-12 12:50:10.378 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:   message   = ""
11-12 12:50:10.378 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:   source file = G:\android-alize-master\alize\src\main\cpp\alize-core\src\FileReader.cpp
11-12 12:50:10.378 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:   line number = 101
11-12 12:50:10.378 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:   fileName =  /data/user/0/com.teamvoicebot.speakerrecognition/files/./world.gmm
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at AlizeSpkRec.SimpleSpkDetSystem.initSystem(Native Method)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at AlizeSpkRec.SimpleSpkDetSystem.<init>(SimpleSpkDetSystem.java:16)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at com.teamvoicebot.speakerrecognition.Main.onCreate(Main.java:62)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.app.Activity.performCreate(Activity.java:6298)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.os.Looper.loop(Looper.java:207)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5896)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
11-12 12:50:10.487 19909-19909/com.teamvoicebot.speakerrecognition W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

[alize.zip](https://github.com/ALIZE-Speaker-Recognition/android-alize/files/1464423/alize.zip)

**Comment by tevamerlin** [comment]
The problem comes from the parameter `inputWorldFilename` in your config file: this parameter tells the system to automatically load the background model from a file with this name, found in the directory specified by `featureFilesPath`, with the extension specified by `loadMixtureFileExtension`.

Use this parameter only if you have put a model file at this path before starting the system.

Otherwise, remove this parameter from the config file, and use one of the `loadBackgroundModel` methods to load the background model after initializing the system.
If your background model is in a file located somewhere else in the filesystem, use the variant taking a filename.
If it is distributed as part of your application assets, open an `InputStream` to access it and pass the stream to the other variant of `loadBackgroundModel`.

**Comment by channae** [comment]
@tevamerlin  Hi, I'm facing the same error. I don't have a background model so I removed this parameter from the config file. How can we provide a new background mode? and appreciate if you could tell me the steps that I should take. Or if there are any sample background models that I can use.

Thanks,
